#:schema node_modules/wrangler/config-schema.json
name = "personal-website"
compatibility_date = "2025-02-04"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./dist"

[observability]
enabled = true

# The rate limiting API is in open beta.
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
# An identifier you define, that is unique to your Cloudflare account.
# Must be an integer.
namespace_id = "1001"

# Limit: the number of tokens allowed within a given period in a single
# Cloudflare location
# Period: the duration of the period, in seconds. Must be either 10 or 60
# Allow 20 requests per minute per IP address
simple = { limit = 20, period = 60 }