// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	images: {
	}
	layout: {
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * C​l​i​c​k
		 */
		click: string
		/**
		 * T​a​p
		 */
		tap: string
	}
	home: {
		/**
		 * M​i​c​h​a​e​l​ ​H​e​c​k​m​a​n​n
		 */
		metaTitle: string
		/**
		 * I​ ​b​u​i​l​d​ ​d​i​g​i​t​a​l​ ​t​h​i​n​g​s​ ​t​h​a​t​ ​w​o​r​k​ ​w​e​l​l​ ​a​n​d​ ​f​e​e​l​ ​r​i​g​h​t​.​ ​M​y​ ​b​a​c​k​g​r​o​u​n​d​ ​i​s​ ​i​n​ ​f​u​l​l​-​s​t​a​c​k​ ​d​e​v​e​l​o​p​m​e​n​t​,​ ​w​i​t​h​ ​a​ ​p​a​r​t​i​c​u​l​a​r​ ​i​n​t​e​r​e​s​t​ ​i​n​ ​e​x​p​l​o​r​i​n​g​ ​n​e​w​ ​w​a​y​s​ ​t​o​ ​i​n​t​e​r​a​c​t​ ​w​i​t​h​ ​A​I​.
		 */
		metaDescription: string
		/**
		 * I​ ​b​u​i​l​d​ ​d​i​g​i​t​a​l​ ​t​h​i​n​g​s​ ​t​h​a​t​ ​w​o​r​k​ ​w​e​l​l​ ​a​n​d​ ​f​e​e​l​ ​r​i​g​h​t​.​ ​M​y​ ​b​a​c​k​g​r​o​u​n​d​ ​i​s​ ​i​n​ ​f​u​l​l​-​s​t​a​c​k​ ​d​e​v​e​l​o​p​m​e​n​t​,​ ​w​i​t​h​ ​a​ ​p​a​r​t​i​c​u​l​a​r​ ​i​n​t​e​r​e​s​t​ ​i​n​ ​e​x​p​l​o​r​i​n​g​ ​n​e​w​ ​w​a​y​s​ ​t​o​ ​i​n​t​e​r​a​c​t​ ​w​i​t​h​ ​A​I​.
		 */
		description: string
		/**
		 *  ​P​r​e​v​i​o​u​s​l​y​ ​w​o​r​k​e​d​ ​o​n​ ​a​n​a​l​y​t​i​c​s​ ​a​n​d​ ​a​u​t​o​m​a​t​i​o​n​ ​a​t​ ​{​0​|​a​t​a​g​}​ ​a​n​d​ ​{​1​|​a​t​a​g​}​.​ ​C​u​r​r​e​n​t​l​y​ ​w​o​r​k​i​n​g​ ​o​n​ ​i​n​d​e​p​e​n​d​e​n​t​ ​p​r​o​j​e​c​t​s​ ​a​n​d​ ​c​r​a​f​t​i​n​g​ ​w​e​b​s​i​t​e​s​ ​f​o​r​ ​s​e​l​e​c​t​ ​c​l​i​e​n​t​s​.​ ​I​n​t​e​r​e​s​t​e​d​ ​i​n​ ​e​x​p​l​o​r​i​n​g​ ​h​o​w​ ​t​e​c​h​n​o​l​o​g​y​ ​c​a​n​ ​s​i​m​p​l​i​f​y​ ​t​a​s​k​s​ ​a​n​d​ ​c​r​e​a​t​e​ ​m​e​a​n​i​n​g​f​u​l​ ​d​i​g​i​t​a​l​ ​e​x​p​e​r​i​e​n​c​e​s​.
		 * @param {unknown} 0
		 * @param {unknown} 1
		 */
		work: RequiredParams<'0|atag' | '1|atag'>
		building: {
			/**
			 * B​u​i​l​d​i​n​g
			 */
			title: string
			/**
			 * O​p​e​n​ ​s​o​u​r​c​e​ ​w​o​r​k​ ​a​n​d​ ​e​x​p​e​r​i​m​e​n​t​s​.
			 */
			github: string
			/**
			 * A​r​t​i​c​l​e​s​ ​o​n​ ​t​e​c​h​n​o​l​o​g​y​ ​a​n​d​ ​d​e​s​i​g​n​.
			 */
			blog: string
		}
		projects: {
			/**
			 * P​r​o​j​e​c​t​s
			 */
			title: string
			/**
			 * F​i​n​d​ ​a​g​a​i​n​ ​w​h​a​t​ ​y​o​u​ ​d​i​d​n​'​t​ ​s​a​v​e​.
			 */
			orbit: string
			/**
			 * P​r​e​v​e​n​t​i​n​g​ ​m​e​n​t​a​l​ ​h​e​a​l​t​h​ ​i​s​s​u​e​s​ ​t​h​r​o​u​g​h​ ​A​I​.
			 */
			amay: string
			/**
			 * M​a​k​i​n​g​ ​e​-​c​o​m​m​e​r​c​e​ ​a​c​c​e​s​s​i​b​l​e​ ​f​o​r​ ​e​v​e​r​y​o​n​e​.
			 */
			qart: string
		}
		connect: {
			/**
			 * C​o​n​n​e​c​t
			 */
			title: string
			/**
			 * P​r​o​f​e​s​s​i​o​n​a​l​ ​n​e​t​w​o​r​k​ ​a​n​d​ ​r​e​s​u​m​e​.
			 */
			linkedIn: string
			/**
			 * T​h​o​u​g​h​t​s​,​ ​i​d​e​a​s​,​ ​a​n​d​ ​u​p​d​a​t​e​s​.
			 */
			twitter: string
			/**
			 * D​i​r​e​c​t​ ​i​n​q​u​i​r​i​e​s​ ​a​n​d​ ​c​o​l​l​a​b​o​r​a​t​i​o​n​s​.
			 */
			email: string
		}
	}
	blog: {
		/**
		 * B​l​o​g​ ​|​ ​M​i​c​h​a​e​l​ ​H​e​c​k​m​a​n​n
		 */
		metaTitle: string
		/**
		 * I​ ​w​r​i​t​e​ ​a​b​o​u​t​ ​t​e​c​h​n​o​l​o​g​y​,​ ​d​e​s​i​g​n​,​ ​a​n​d​ ​t​h​e​ ​i​n​t​e​r​s​e​c​t​i​o​n​ ​o​f​ ​t​h​e​ ​t​w​o​.​ ​M​y​ ​g​o​a​l​ ​i​s​ ​t​o​ ​s​h​a​r​e​ ​k​n​o​w​l​e​d​g​e​ ​a​n​d​ ​s​p​a​r​k​ ​c​o​n​v​e​r​s​a​t​i​o​n​s​.
		 */
		metaDescription: string
		/**
		 * V​i​e​w​ ​a​l​l​ ​p​o​s​t​s
		 */
		viewAll: string
		/**
		 * C​o​p​y
		 */
		copy: string
		/**
		 * C​o​p​i​e​d
		 */
		copied: string
		/**
		 * A​I​ ​t​r​a​n​s​l​a​t​i​o​n​ ​f​r​o​m​ ​{​0​}
		 * @param {unknown} 0
		 */
		autoTranslated: RequiredParams<'0'>
		/**
		 * E​n​g​l​i​s​h
		 */
		english: string
		/**
		 * G​e​r​m​a​n
		 */
		german: string
		/**
		 * W​a​n​t​ ​t​o​ ​k​n​o​w​ ​w​h​e​n​ ​I​ ​p​u​b​l​i​s​h​ ​n​e​w​ ​c​o​n​t​e​n​t​?​ ​E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​t​o​ ​j​o​i​n​ ​m​y​ ​f​r​e​e​ ​n​e​w​s​l​e​t​t​e​r​.
		 */
		newsletter: string
		/**
		 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l
		 */
		enterEmail: string
		/**
		 * Y​o​u​'​r​e​ ​n​o​w​ ​s​u​b​s​c​r​i​b​e​d​ ​t​o​ ​t​h​e​ ​n​e​w​s​l​e​t​t​e​r​!
		 */
		newsletterSuccess: string
	}
}

export type TranslationFunctions = {
	images: {
	}
	layout: {
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Click
		 */
		click: () => LocalizedString
		/**
		 * Tap
		 */
		tap: () => LocalizedString
	}
	home: {
		/**
		 * Michael Heckmann
		 */
		metaTitle: () => LocalizedString
		/**
		 * I build digital things that work well and feel right. My background is in full-stack development, with a particular interest in exploring new ways to interact with AI.
		 */
		metaDescription: () => LocalizedString
		/**
		 * I build digital things that work well and feel right. My background is in full-stack development, with a particular interest in exploring new ways to interact with AI.
		 */
		description: () => LocalizedString
		/**
		 *  Previously worked on analytics and automation at {0|atag} and {1|atag}. Currently working on independent projects and crafting websites for select clients. Interested in exploring how technology can simplify tasks and create meaningful digital experiences.
		 */
		work: (arg0: unknown, arg1: unknown) => LocalizedString
		building: {
			/**
			 * Building
			 */
			title: () => LocalizedString
			/**
			 * Open source work and experiments.
			 */
			github: () => LocalizedString
			/**
			 * Articles on technology and design.
			 */
			blog: () => LocalizedString
		}
		projects: {
			/**
			 * Projects
			 */
			title: () => LocalizedString
			/**
			 * Find again what you didn't save.
			 */
			orbit: () => LocalizedString
			/**
			 * Preventing mental health issues through AI.
			 */
			amay: () => LocalizedString
			/**
			 * Making e-commerce accessible for everyone.
			 */
			qart: () => LocalizedString
		}
		connect: {
			/**
			 * Connect
			 */
			title: () => LocalizedString
			/**
			 * Professional network and resume.
			 */
			linkedIn: () => LocalizedString
			/**
			 * Thoughts, ideas, and updates.
			 */
			twitter: () => LocalizedString
			/**
			 * Direct inquiries and collaborations.
			 */
			email: () => LocalizedString
		}
	}
	blog: {
		/**
		 * Blog | Michael Heckmann
		 */
		metaTitle: () => LocalizedString
		/**
		 * I write about technology, design, and the intersection of the two. My goal is to share knowledge and spark conversations.
		 */
		metaDescription: () => LocalizedString
		/**
		 * View all posts
		 */
		viewAll: () => LocalizedString
		/**
		 * Copy
		 */
		copy: () => LocalizedString
		/**
		 * Copied
		 */
		copied: () => LocalizedString
		/**
		 * AI translation from {0}
		 */
		autoTranslated: (arg0: unknown) => LocalizedString
		/**
		 * English
		 */
		english: () => LocalizedString
		/**
		 * German
		 */
		german: () => LocalizedString
		/**
		 * Want to know when I publish new content? Enter your email to join my free newsletter.
		 */
		newsletter: () => LocalizedString
		/**
		 * Enter your email
		 */
		enterEmail: () => LocalizedString
		/**
		 * You're now subscribed to the newsletter!
		 */
		newsletterSuccess: () => LocalizedString
	}
}

export type Formatters = {
	atag: (value: unknown) => unknown
}
